set_property PACKAGE_PIN AC21 [get_ports {a}]
set_property PACKAGE_PIN AD24 [get_ports {b}]
set_property PACKAGE_PIN AC22 [get_ports {cin}]
set_property PACKAGE_PIN H7 [get_ports {sum}]
set_property PACKAGE_PIN D5 [get_ports {cout}]

set_property IOSTANDARD LVCMOS33 [get_ports {a}]
set_property IOSTANDARD LVCMOS33 [get_ports {b}]
set_property IOSTANDARD LVCMOS33 [get_ports {cin}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout}]
